name: nanopore_py27
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2019.11.28=py27h8c360ce_1
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_5
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libzlib=1.2.13=h4ab18f5_6
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - mysql-python=1.2.5=py27h7f98852_0
  - ncurses=6.5=h2d0b736_3
  - openssl=1.1.1w=hd590300_0
  - pip=20.1.1=pyh9f0ad1d_0
  - python=2.7.15=h5a48372_1011_cpython
  - python_abi=2.7=1_cp27mu
  - readline=8.3=h853b02a_0
  - setuptools=44.0.0=py27_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.37.1=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - backports-abc==0.5
      - backports-functools-lru-cache==1.6.6
      - backports-shutil-get-terminal-size==1.0.0
      - cycler==0.10.0
      - cython==0.29.37
      - decorator==4.4.2
      - enum34==1.1.10
      - futures==3.4.0
      - ipykernel==4.10.1
      - ipython==5.10.0
      - ipython-genutils==0.2.0
      - jupyter-client==5.3.5
      - jupyter-core==4.6.3
      - kiwisolver==1.1.0
      - matplotlib==2.2.5
      - networkx==1.11
      - numpy==1.16.6
      - pandas==0.24.2
      - pathlib2==2.3.7.post1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - prompt-toolkit==1.0.18
      - ptyprocess==0.7.0
      - pygments==2.5.2
      - pyparsing==2.4.7
      - python-dateutil==2.9.0.post0
      - pythonic-porin==0.2.1
      - pytz==2025.2
      - pyzmq==19.0.2
      - scandir==1.10.0
      - scipy==1.2.3
      - seaborn==0.9.1
      - simplegeneric==0.8.1
      - singledispatch==3.7.0
      - six==1.17.0
      - subprocess32==3.5.4
      - tornado==5.1.1
      - traitlets==4.3.3
      - typing==3.10.0.0
      - wcwidth==0.2.13
      - yahmm==1.1.3
prefix: /home/jesse/miniforge3/envs/nanopore_py27
